### ISSUE TITLE
동적으로 mapper scan 하는 구현에 해당 소스로 큰 도움 받고 있습니다.  추가로 문의 사항있습니다

### ISSUE THREAD

**Issue by coolwis** [ysjee141/dynamic-mapper-scanner#1]
선생님의 소스 덕분에   mapper scan을 동적으로 데이터소스와 연결하는 기능을 위해서 도움이 됩니다.

요구사항 중에     동적으로 디비 여러개를 application.properties에  등록하면 
자동으로 데이터소스와  MapperScan 처리 해서      화면에서 선택한 디비로 쿼리를 할 수 있게 해 달라고 합니다.

위의 소스에서  디비를 동적으로 여러개 등록해서 사용 가능할까요? 
application.properties에만 등록하면 자동으로 생성 되도록 하려고 합니다.
dbConfig 클래스를  디비 갯수 만큼 추가 하고  자동화 하려는데   
동적으로  mapperScan과 sqlSessionFactory 연결에서 잘 안되네요

**Comment by ysjee141** [comment]
@coolwis 
문의하시는 부분이 DataSource는 여러개이나 MapperScan은 하나로 DB의 Switch 기능을 말씀하신는 부분일까요?

**Comment by coolwis** [comment]
궁극적인 기능은 사용자가 선택한 디비에 따라서 쿼리가 되도록 하는 스위칭 기능입니다.

현재는 application.proporities에  디비를 추가하면   그것에 해당하는 DBConfig 클래스를 추가로 만들고 
거기에  Mapperscan과 sqlSessionFactory 빈을 연결하는 코드도 만들고 추가 작업을 합니다.
그런 추가 작업을 하지 않도록 
디비 갯수 대로   dataSource생성 후  MapperScan과 연결 되도록  공통클래스를 만들어야 되는데 
그 부분이 막히고 있습니다.  
(springboot2, mybatis환경입니다)

**Comment by ysjee141** [comment]
@coolwis 본 코드의 
https://github.com/ysjee141/dynamic-mapper-scanner/blob/907b300d5e18a957fc688c1ad84516bc68a724cf/src/main/java/com/example/dynamicmapperscanner/config/MapperBeanPostProcessor.java#L80-L94

부분이 application.properties(application.yml)내 설정된 datasource 를 bean으로 등록하는 부분입니다.
사용자의 선택에 따른 동적 Switch 기능이라면 선택한 DataSource를 ThreadLocal에 저장해서 호출하시면 될 듯합니다.
DataSource 자체가 동적 Bean으로 설정되어서, 가지고 오시려면, ApplicationContext를 통해서 DataSource BeanName으로 Bean을 호출해서 지정하시면 될 듯합니다.

만약 WebFlux 환경을 쓰시고 계시다면 ThreadLocal은 유효하지 않아서 별도로 ContextHolder를 생성하셔야 할 것 같네요~

**Comment by coolwis** [comment]
네 답변 감사드립니다.
디비 여러개 설정하려면
application.properties에서 어떻게 추가 되어 있어야 하는지 알려주시면 감사하겠습니다
아래처럼 여러개추가 되는것인지요?
datasource3:
  - name: datasourceOne
  -~~~~
  -name: datasourceTwo

**Comment by ysjee141** [comment]
@coolwis 말씀하신 것과 같습니다.
현재 https://github.com/ysjee141/dynamic-mapper-scanner/blob/907b300d5e18a957fc688c1ad84516bc68a724cf/src/main/java/com/example/dynamicmapperscanner/config/MapperConfig.java#L20 쪽에 prefix를 datasource3로 잡아 놓아서 그 하위에 Array 형식으로 DataSource를 선언하여 주시면 됩니다.
Array Element의 type은 https://github.com/ysjee141/dynamic-mapper-scanner/blob/907b300d5e18a957fc688c1ad84516bc68a724cf/src/main/java/com/example/dynamicmapperscanner/config/RepoConfig.java#L43 여기를 참고하시면 될 것 같네요.

제가 작업한 BeanPostProcessor에서는 MapperOrder를 통해 Annotation을 강제하여서 2개까지만 사용이 가능한 부분으로 되어 있는데, 위와 같이 DataSource를 ThreadLocal을 통해 Control하면 Limit는 무관할 것 같네요.

오래전에 만들었던 코드라 지금 보니 고쳐야할 부분이 많네요...ㅎㅎ;; 
모쪼록 도움이 되었으면 좋겠습니다.

**Comment by coolwis** [comment]
동적으로 mapperscanner 빈 등록이 필요했는데  큰 도움 되고 있습니다
감사합니다
